### ISSUE TITLE
add PyTorch-Style-Transfer please

### ISSUE THREAD

**Issue by acgtyrant** [rickiepark/awesome-pytorch#2]
[PyTorch-Style-Transfer](https://github.com/zhanghang1989/PyTorch-Style-Transfer): Multi-style Generative Network for Real-time Transfer, [1703.06953](https://arxiv.org/pdf/1703.06953.pdf)
[PyTorch-Style-Transfer](https://github.com/zhanghang1989/PyTorch-Style-Transfer): Image Style Transfer Using Convolutional Neural Networks, [pdf](http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf)

**Comment by rickiepark** [comment]
Thanks!
