### ISSUE TITLE
add pytorch-playground please

### ISSUE THREAD

**Issue by acgtyrant** [rickiepark/awesome-pytorch#3]
[pytorch-playground](https://github.com/aaron-xichen/pytorch-playground): Base pretrained models and datasets in pytorch (MNIST, SVHN, CIFAR10, CIFAR100, STL10, AlexNet, VGG16, VGG19, ResNet, Inception, SqueezeNet)

You can put it in the Tutorials & Examples section.

**Comment by rickiepark** [comment]
Thanks!
